version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
  exclusions:
    paths:
      - internal/gounifi

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - internal/gounifi
