version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/claytono/go-unifi-mcp

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    colored-line-number: {}
  sort-results: true
